### ISSUE TITLE
CW解析プラグインが急に落ちる

### ISSUE THREAD

**Issue by jucky154** [nextzlog/todo#102]
## 概要
CW解析プラグインが急に落ちるとの報告をZLOの部員から受けた

## 再現手順・設定
環境としてはUbuntuでwineを使っていたらしい
```
panic: runtime error: makeslice: len out of range

goroutine 54266954 [running]:
main.Decode({0x676ceaf8, 0x0, 0x0})
        /home/runner/work/cwListener/cwListener/cwListener.go:460 +0x59
main.decode_main({0xc0021d6000, 0x2ef14, 0xc0002c8030?}, 0xac44)
        /home/runner/work/cwListener/cwListener/cwListener.go:353 +0x434
created by main.initdevice.func3
        /home/runner/work/cwListener/cwListener/cwListener.go:802 +0x2f1
```

がエラーコード
## 期待される動作
落ちないようにする

## 対応期限
ACAGまで？

**Comment by jucky154** [comment]
落ちている場所は解析に回すためのsliceを作るとき

一般に負の値が入るか、無茶苦茶大きな値が入ることが原因

負の値は絶対に入らない（最低1秒以上は解析するようにしているので）ので、無茶苦茶大きな値が入るせいで起きたと考えられる
対策としては、44100Hzでやっているのでどれくらいがいいか検討がつかないが、60秒を超えるような内容はないと考えられるので、60*44100を上限にするとかでスライスを作るべきだと考えられる

**Comment by jucky154** [comment]
https://github.com/jucky154/cwListener/commit/111d867d03b625b46baa0f90fab44837226f009b
これだけは急いで修正するべき事項だと思ったので修正
