### ISSUE TITLE
ATS-4 が正常に稼働しない

### ISSUE THREAD

**Issue by irukabando** [nextzlog/todo#230]
個人的興味で，ATS-4 を稼働させようとしています。（コンテスト運営するわけではないので特に急ぎません！）

windows 10 で docker desktop をインストールし，WSL で https://github.com/nextzlog/ats4 にある Quick Start のコマンドを実行しましたが，localhost にブラウザでアクセスしても，「正常に表示できません」と出ました。

docker desktop の container というところを見ましたら，WWW-1 も ATAS4-1 というコンテナも停止してしまっているようでした。

`docker compose up -d`
でコンテナの起動だと思いますが，これを実行すると，

```
WARN[0000] The "name" variable is not set. Defaulting to a blank string.
WARN[0000] /home/jp7vsw/docker-compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Running 2/0
 ✔ Container jp7vsw-ATS4-1  Created                                                                             0.0s[+] Running 2/2
 ✔ Container jp7vsw-ATS4-1  Started                                                                             0.6s ⠴ Container jp7vsw-www-1   Starting                                                                            0.5s
 ✔ Container jp7vsw-www-1   Started   
```

と出ました。
ここに，出ている warnig が原因なのでしょうか...?

また，docker desktop の terminal には
www-1 というコンテナには，

```
2024-12-11 03:44:27 /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
2024-12-11 03:44:27 /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
2024-12-11 03:44:27 /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
2024-12-11 03:44:27 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
2024-12-11 03:44:27 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
2024-12-11 03:44:27 /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
2024-12-11 03:44:27 /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
2024-12-11 03:44:27 /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
2024-12-11 03:44:27 /docker-entrypoint.sh: Configuration complete; ready for start up
2024-12-11 03:44:27 2024/12/10 18:44:27 [emerg] 1#1: directive "server_name" is not terminated by ";" in /etc/nginx/conf.d/default.conf:2
2024-12-11 03:44:27 nginx: [emerg] directive "server_name" is not terminated by ";" in /etc/nginx/conf.d/default.conf:2
```

ATAS4-1 というコンテナのターミナルは，

```
2024-12-11 03:42:56 03:42:55,580 |-INFO in ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version 1.5.6
2024-12-11 03:42:56 03:42:55,589 |-INFO in ch.qos.logback.classic.util.ContextInitializer@7dc0f706 - No custom configurators were discovered as a service.
2024-12-11 03:42:56 03:42:55,589 |-INFO in ch.qos.logback.classic.util.ContextInitializer@7dc0f706 - Trying to configure with ch.qos.logback.classic.joran.SerializedModelConfigurator
2024-12-11 03:42:56 03:42:55,592 |-INFO in ch.qos.logback.classic.util.ContextInitializer@7dc0f706 - Constructed configurator of type class ch.qos.logback.classic.joran.SerializedModelConfigurator
2024-12-11 03:42:56 03:42:55,608 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.scmo]
2024-12-11 03:42:56 03:42:55,610 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.scmo]
2024-12-11 03:42:56 03:42:55,644 |-INFO in ch.qos.logback.classic.util.ContextInitializer@7dc0f706 - ch.qos.logback.classic.joran.SerializedModelConfigurator.configure() call lasted 18 milliseconds. ExecutionStatus=INVOKE_NEXT_IF_ANY
2024-12-11 03:42:56 03:42:55,644 |-INFO in ch.qos.logback.classic.util.ContextInitializer@7dc0f706 - Trying to configure with ch.qos.logback.classic.util.DefaultJoranConfigurator
2024-12-11 03:42:56 03:42:55,645 |-INFO in ch.qos.logback.classic.util.ContextInitializer@7dc0f706 - Constructed configurator of type class ch.qos.logback.classic.util.DefaultJoranConfigurator
2024-12-11 03:42:56 03:42:55,647 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
2024-12-11 03:42:56 03:42:55,662 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/ats/conf/logback.xml]
2024-12-11 03:42:56 03:42:56,063 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [FILE]
2024-12-11 03:42:56 03:42:56,063 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
2024-12-11 03:42:56 03:42:56,095 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
2024-12-11 03:42:56 03:42:56,137 |-INFO in ch.qos.logback.core.FileAppender[FILE] - File property is set to [./logs/application.log]
2024-12-11 03:42:56 03:42:56,139 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [STDOUT]
2024-12-11 03:42:56 03:42:56,139 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
2024-12-11 03:42:56 03:42:56,140 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
2024-12-11 03:42:56 03:42:56,141 |-INFO in ch.qos.logback.core.ConsoleAppender[STDOUT] - Enabling JANSI AnsiPrintStream for the console.
2024-12-11 03:42:56 03:42:56,141 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - Failed to create AnsiPrintStream. Falling back on the default stream. java.lang.ClassNotFoundException: org.fusesource.jansi.AnsiConsole
2024-12-11 03:42:56 at java.lang.ClassNotFoundException: org.fusesource.jansi.AnsiConsole
2024-12-11 03:42:56 at at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
2024-12-11 03:42:56 at at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
2024-12-11 03:42:56 at at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
2024-12-11 03:42:56 at at ch.qos.logback.core.ConsoleAppender.wrapWithJansi(ConsoleAppender.java:101)
2024-12-11 03:42:56 at at ch.qos.logback.core.ConsoleAppender.start(ConsoleAppender.java:91)
2024-12-11 03:42:56 at at ch.qos.logback.core.model.processor.AppenderModelHandler.postHandle(AppenderModelHandler.java:84)
2024-12-11 03:42:56 at at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:257)
2024-12-11 03:42:56 at at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
2024-12-11 03:42:56 at at ch.qos.logback.core.model.processor.DefaultProcessor.traversalLoop(DefaultProcessor.java:90)
2024-12-11 03:42:56 at at ch.qos.logback.core.model.processor.DefaultProcessor.process(DefaultProcessor.java:106)
2024-12-11 03:42:56 at at ch.qos.logback.core.joran.GenericXMLConfigurator.processModel(GenericXMLConfigurator.java:216)
2024-12-11 03:42:56 at at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:178)
2024-12-11 03:42:56 at at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:123)
2024-12-11 03:42:56 at at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:66)
2024-12-11 03:42:56 at at ch.qos.logback.classic.util.DefaultJoranConfigurator.configureByResource(DefaultJoranConfigurator.java:68)
2024-12-11 03:42:56 at at ch.qos.logback.classic.util.DefaultJoranConfigurator.configure(DefaultJoranConfigurator.java:35)
2024-12-11 03:42:56 at at ch.qos.logback.classic.util.ContextInitializer.invokeConfigure(ContextInitializer.java:128)
2024-12-11 03:42:56 at at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:103)
2024-12-11 03:42:56 at at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:66)
2024-12-11 03:42:56 at at ch.qos.logback.classic.spi.LogbackServiceProvider.initializeLoggerContext(LogbackServiceProvider.java:52)
2024-12-11 03:42:56 at at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:41)
2024-12-11 03:42:56 at at org.slf4j.LoggerFactory.bind(LoggerFactory.java:196)
2024-12-11 03:42:56 at at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:183)
2024-12-11 03:42:56 at at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:486)
2024-12-11 03:42:56 at at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:472)
2024-12-11 03:42:56 at at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:421)
2024-12-11 03:42:56 at at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:447)
2024-12-11 03:42:56 at at play.api.Configuration$.<clinit>(Configuration.scala:196)
2024-12-11 03:42:56 at at play.core.server.ProdServerStart$.readServerConfigSettings(ProdServerStart.scala:101)
2024-12-11 03:42:56 at at play.core.server.ProdServerStart$.start(ProdServerStart.scala:41)
2024-12-11 03:42:56 at at play.core.server.ProdServerStart$.main(ProdServerStart.scala:28)
2024-12-11 03:42:56 at at play.core.server.ProdServerStart.main(ProdServerStart.scala)
2024-12-11 03:42:56 03:42:56,142 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to INFO
2024-12-11 03:42:56 03:42:56,148 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [FILE] to Logger[ROOT]
2024-12-11 03:42:56 03:42:56,148 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [STDOUT] to Logger[ROOT]
2024-12-11 03:42:56 03:42:56,148 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@5fbe4146 - End of configuration.
2024-12-11 03:42:56 03:42:56,150 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@1e66f1f5 - Registering current configuration as safe fallback point
2024-12-11 03:42:56 03:42:56,150 |-INFO in ch.qos.logback.classic.util.ContextInitializer@7dc0f706 - ch.qos.logback.classic.util.DefaultJoranConfigurator.configure() call lasted 505 milliseconds. ExecutionStatus=DO_NOT_INVOKE_NEXT_IF_ANY
2024-12-11 03:42:56 
2024-12-11 03:42:56 This application is already running (or delete /ats/RUNNING_PID file).
```

と出ていました。

雑ですみませんが，対処法などご存じだったりしませんでしょうか。

**Comment by JG1VPP** [comment]
原因はよくわかりませんが、以下のメッセージが気になります。

```
2024-12-11 03:42:56 This application is already running (or delete /ats/RUNNING_PID file).
```

`RUNNING_PID`はATS-4のプロセスIDを記録するファイルで、作成済みの場合は2重起動を避けるためATS-4が起動しません。このファイルはDockerコンテナの中にあるため、通常はこのようなエラーは発生しないはずです。

いちどDockerイメージを最新のものに差し替えて実行し直すと直るかもしれません。

```sh
$ docker pull ghcr.io/nextzlog/ats4:master
```
