### ISSUE TITLE
【電通大コンテスト】システム更新

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#64]
## 概要

電通大コンテストのATS-4の改修内容と必要な更新作業をまとめる。

**Comment by JG1VPP** [comment]
## 更新内容

### 交信記録ファイル

- [HAMLOG HDB対応](https://github.com/nextzlog/todo/issues/20)
- [ZLOファイルのタイムゾーンがUTCになる問題の解消](https://github.com/nextzlog/todo/issues/29)
- [SWL専用の受信記録ファイルへの対応](https://github.com/nextzlog/todo/issues/60)

### 提出画面

- [郵便番号から住所を自動入力](https://github.com/nextzlog/todo/issues/24)
- [交信記録を作成する画面の追加](https://github.com/nextzlog/todo/issues/30)
- [シングルバンド部門で異なる2種の部門への登録に対応](https://github.com/nextzlog/todo/issues/31)
- [多重送信の防止](https://github.com/nextzlog/todo/issues/38)
- [SWLナンバーへの対応](https://github.com/nextzlog/todo/issues/55)

### 管理画面

- [最提出画面で以前のファイルを保持](https://github.com/nextzlog/todo/issues/49)

### ヘルプ画面

- [コンテストに特有のヘルプを表示](https://github.com/nextzlog/todo/issues/59)

### ルック・アンド・フィール

- [Bootstrap5移行](https://github.com/nextzlog/todo/issues/50)

### システム内部

- [ORMの廃止](https://github.com/nextzlog/todo/issues/25)
- [規約をDIで注入](https://github.com/nextzlog/todo/issues/34)

### ストリーミング

- [結果発表前に集計結果が漏洩する問題の解消](https://github.com/nextzlog/todo/issues/52)

### ドキュメント整備

- [Scaladoc](https://github.com/nextzlog/todo/issues/37)

### 実行環境

- [Dockerイメージの生成](https://github.com/nextzlog/todo/issues/21)

### その他

- [ZyLOへのリンクを追加](https://github.com/nextzlog/todo/issues/40)

**Comment by JG1VPP** [comment]
## 更新作業

1. ATS-4を停止する
2. `ats4/target/universal/stage/data/ats4.mv.db`を厳重にバックアップする（重要）
3. ATS-4をクローンし直して、ディレクトリごと最新のものに置き換える（`git pull`よりも推奨）
4. ATS-4の設定をやり直す（主に、`ats4.rules`とメール関連）
5. `ats4.mv.db`に対し、[スキーマの変換](https://github.com/nextzlog/todo/issues/51)を行う
6. ATS-4を起動する

**Comment by JG1VPP** [comment]
@karyuda
8月31日になりましたら、以上の作業をお願いします。質問があれば何でも仰ってください。

**Comment by JG1VPP** [comment]
ZGPに引き渡すための最終準備中

**Comment by JG1VPP** [comment]
ZGPに引き渡すのと同じバージョンが[リアルタイムコンテスト](https://realtime.allja1.org/)で稼働中

**Comment by karyuda** [comment]
ATS-4の更新作業を行いましたが、データベースのスキーマ変換で以下のエラーが出ました。

```
uectest-info@ik1-436-50418:/srv/ats4/target/universal/stage$ ls
README.md  ats4.mv.db  ats4.trace.db  bin  conf  lib  logs  share
uectest-info@ik1-436-50418:/srv/ats4/target/universal/stage$ java -cp ~/tmp/h2/bin/h2-1.4.200.jar org.h2.tools.RunScript -url "jdbc:h2:file:./data/ats4" -user sa -script ~/tmp/alter.sql -showResults                                          ALTER TABLE IF EXISTS STATION_DATAS RENAME TO STATION_DATA;
ALTER TABLE IF EXISTS RANKING_DATAS RENAME TO RANKING_DATA;
ALTER TABLE IF EXISTS LOG_BOOK_DATAS RENAME TO ARCHIVE_DATA;

ALTER TABLE IF EXISTS RANKING_DATA ALTER COLUMN IF EXISTS MARK RENAME TO SCORE;
ALTER TABLE IF EXISTS RANKING_DATA ALTER COLUMN IF EXISTS RATE RENAME TO TOTAL;
ALTER TABLE IF EXISTS RANKING_DATA DROP COLUMN CODE;

ALTER TABLE IF EXISTS ARCHIVE_DATA ADD COLUMN IF NOT EXISTS FILE VARCHAR(64) AUTO_INCREMENT;

UPDATE RANKING_DATA SET SECT=REPLACE(SECT, '個人部門 (09:00-12:00) 不参加', '個人部門 09:00-12:00 不参加 (チェックログ)');Exception in thread "main" org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "RANKING_DATA" not found; SQL statement:


UPDATE RANKING_DATA SET SECT=REPLACE(SECT, '個人部門 (09:00-12:00) 不参加', '個人部門 09:00-12:00 不参加 (チェックログ)') [42102-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
        at org.h2.message.DbException.get(DbException.java:205)
        at org.h2.message.DbException.get(DbException.java:181)
        at org.h2.command.Parser.readTableOrView(Parser.java:7628)
        at org.h2.command.Parser.readTableOrView(Parser.java:7599)
        at org.h2.command.Parser.readSimpleTableFilter(Parser.java:1350)
        at org.h2.command.Parser.parseUpdate(Parser.java:1288)
        at org.h2.command.Parser.parsePrepared(Parser.java:1005)
        at org.h2.command.Parser.parse(Parser.java:843)
        at org.h2.command.Parser.parse(Parser.java:815)
        at org.h2.command.Parser.prepareCommand(Parser.java:738)
        at org.h2.engine.Session.prepareLocal(Session.java:657)
        at org.h2.engine.Session.prepareCommand(Session.java:595)
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:212)
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201)
        at org.h2.tools.RunScript.process(RunScript.java:224)
        at org.h2.tools.RunScript.process(RunScript.java:192)
        at org.h2.tools.RunScript.process(RunScript.java:328)
        at org.h2.tools.RunScript.runTool(RunScript.java:143)
        at org.h2.tools.RunScript.main(RunScript.java:70)
```

**Comment by JG1VPP** [comment]
以下を実行して、テーブルのリストを表示します。

```sql
show tables;
```

ここで以下の出力が得られるはずです。

```sql
--> ARCHIVE_DATA PUBLIC
--> RANKING_DATA PUBLIC
--> STATION_DATA PUBLIC
```

もし何も表示されないようであれば、データベースには何も登録されていません。そうでなければ、dbファイルのパスが間違っている可能性があります。間違いなく、`./data/ats4.mv.db`ファイルが存在しますか？

**Comment by JG1VPP** [comment]
もし誤ったパスを指定してH2DBを起動すると、そのパスでdbファイルが生成されるので、その点に注意して確認をお願いします。

**Comment by karyuda** [comment]
パスが間違っていました。
データベースのスキーマ変換ができました。
ご回答ありがとうございます。

**Comment by karyuda** [comment]
アップデートが完了し、書類提出を試みましたが、以下のissueの現象が発生しました。
ご対応いただけますと幸いです。
https://github.com/nextzlog/todo/issues/81
