### ISSUE TITLE
【電通大コンテスト】交信記録の書式の自動判別機能

### ISSUE THREAD

**Issue by karyuda** [nextzlog/todo#81]
## 概要
交信記録の書式の自動判別機能において対応と未対応の判定が逆になっており、書類提出ができません。

## 再現手順・設定
こちらでアップデートした電通大コンテストのATS-4と稼働したいただいたリアルタイムコンテストのATS-4のどちらでも、同様に以下の現象を確認しました。

書類提出時のファイル選択において、

正常なログ(アップデート以前に提出できたログ)を選択した場合
=>"交信記録の書式が崩れているか、未対応です。"と表示

自作ログなどの以前は提出できなかったログや中身が全く関係ないtxtファイルなどを選択した場合
=>"この交信記録は対応済みです。受理可能です。"と表示

どちらの場合も提出した場合はログが読み込まれず、得点が0点になります。

## 期待される動作
正常なログ(アップデート以前に提出できたログ)を選択した場合、"この交信記録は対応済みです。受理可能です。"と表示される。

**Comment by JG1VPP** [comment]
@karyuda お待たせしました。`master`ブランチの最新のコミットをご利用ください。大変ご迷惑をお掛けしました。引き続きよろしくお願いいたします。

**Comment by JG1VPP** [comment]
@karyuda 大変ご迷惑をお掛けしました。`master`ブランチの最新のコミットをご利用ください。修正後、読み取り可能なファイルと不可能なファイルの組み合わせを何通りかテストしましたが、仕様通りに提出できました。引き続きよろしくお願いいたします。

**Comment by karyuda** [comment]
ご対応ありがとうございます。
アップデートしました。
自動判別機能が正しく動作するようになりました。

しかし、ログを提出してもログが読み取られません。
下の写真のようになってしまいます。
そちらの環境では、提出時に正しく結果が表示されますでしょうか？
![スクリーンショット (124)](https://user-images.githubusercontent.com/79682961/188924686-856b8f05-f222-4b14-9fdc-a996d6572fd3.png)

**Comment by JG1VPP** [comment]
@karyuda 我々の方では提出できます。

### 考えうる原因

提出ができない理由は、恐らくアップロード時の一時ファイル名が長すぎるためと当たりを付けていますが、そのパッチが正しく適用されているかを確認します。

### 状況確認

まず、ATS-4のバージョンを確認します。以下のハッシュが出力されなければなりません。

```sh
$ git show -s --format=%H
7b926183e41ed99d7860ae2711d83c3d09a6a8fa
```

次に、ローカルの差分を確認します。ここで、設定ファイル以外に差分が存在してはなりません。

```sh
$ git diff --name-only
conf/application.conf
```

**Comment by JG1VPP** [comment]
## クリーンインストール

また、このパッチはQxSLライブラリ側にも跨るものなので、正しくインストールされているかを確認してください。まず、

```sh
$ sbt csrCacheDirectory
/path/to/caches/coursier/v1
```

これで、キャッシュディレクトリが取得できるので、その中身を確認し、適宜クリアしてください。

```sh
$ find </path/to/caches/coursier/v1>/https/nextzlog.github.io/qxsl/mvn/qxsl/qxsl/0.1.268
https/nextzlog.github.io/qxsl/mvn/qxsl/qxsl/0.1.268
https/nextzlog.github.io/qxsl/mvn/qxsl/qxsl/0.1.268/.qxsl-0.1.268.jar.checked
https/nextzlog.github.io/qxsl/mvn/qxsl/qxsl/0.1.268/.qxsl-0.1.268.pom.checked
https/nextzlog.github.io/qxsl/mvn/qxsl/qxsl/0.1.268/qxsl-0.1.268.jar.sha1
https/nextzlog.github.io/qxsl/mvn/qxsl/qxsl/0.1.268/qxsl-0.1.268.pom
https/nextzlog.github.io/qxsl/mvn/qxsl/qxsl/0.1.268/.qxsl-0.1.268.jar.sha1.checked
https/nextzlog.github.io/qxsl/mvn/qxsl/qxsl/0.1.268/qxsl-0.1.268.jar
https/nextzlog.github.io/qxsl/mvn/qxsl/qxsl/0.1.268/.qxsl-0.1.268.pom__sha1.computed
https/nextzlog.github.io/qxsl/mvn/qxsl/qxsl/0.1.268/qxsl-0.1.268.pom.sha1
https/nextzlog.github.io/qxsl/mvn/qxsl/qxsl/0.1.268/.qxsl-0.1.268.pom.sha1.checked
https/nextzlog.github.io/qxsl/mvn/qxsl/qxsl/0.1.268/.qxsl-0.1.268.jar__sha1.computed
$ rm -r </path/to/caches/coursier/v1>/https/nextzlog.github.io
```

クリアした後に、ATS-4をリビルドします。その際に、データベースを適宜退避・復元してください。

```
$ cp target/universal/stage/data/ats4.mv.db /path/to/backup
$ sbt clean
$ sbt stage
$ cp /path/to/backup target/universal/stage/data/ats4.mv.db
$ sbt start
```

以上のような操作は、本来必要のないことです。場合によっては、レポジトリを丸ごとクローンし直した方が手っ取り早いでしょう。

## 推奨

ATS-4では、Dockerイメージを提供しています。
ローカルにsbtの環境を構築することなく、必要なライブラリ等のインストールが万全の状態でATS-4を起動できるので、導入をご検討ください。

**Comment by JG1VPP** [comment]
## Dockerイメージ

https://github.com/nextzlog/ats4/pkgs/container/ats4

このイメージをpullするには、DockerでGitHubにログインしている必要があります。詳細は[ヘルプ](https://docs.github.com/ja/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry)を確認してください。

**Comment by JG1VPP** [comment]
## 正常に稼働中のATS-4

[リアルタイムコンテスト](https://realtime.allja1.org/)で書類提出の動作を確認できます。こちらはデモ中で、今のところ試しに提出していただいても差し支えありません。

**Comment by JG1VPP** [comment]
@karyuda 以下のコマンドの結果だけでも教えていただけないでしょうか？

```
$ git show -s --format=%H
$ git diff --name-only
```

**Comment by karyuda** [comment]
遅くなり申し訳ございません。
以下の結果となりました。
uec.rbはメールアドレス表記変更の差分が出ました。
恐らくこの部分は正常だと思われます。
```$ git show -s --format=%H
7b926183e41ed99d7860ae2711d83c3d09a6a8fa
````
```
$ git diff --name-only
conf/application.conf
conf/rules/JA1ZGP/uec.rb
```

**Comment by JG1VPP** [comment]
なるほど。次に疑わしいのは、ライブラリのキャッシュなのですが、`build.sbt`から

```sbt
"qxsl" % "qxsl" % "0.1.268"
```

の行を削除し、次にATS-4のレポジトリ直下に`lib`ディレクトリを作成し、そこに[`qxsl.jar`](https://github.com/nextzlog/qxsl/raw/gh-pages/mvn/qxsl/qxsl/0.1.268/qxsl-0.1.268.jar)を置き、`sbt clean`してから、再起動するとどうでしょうか？ちなみにこの作業でデータベースが初期化されるので、注意してください。

**Comment by JG1VPP** [comment]
なるほど。であれば、想定していた原因ではなさそうです。

ファイルの提出ができない原因は、恐らく[tasks.scala #L75-80](https://github.com/nextzlog/ats4/blob/7b926183e41ed99d7860ae2711d83c3d09a6a8fa/app/tasks/tasks.scala#L75-L80)で何らかの例外が発生しているはずです。その行を、以下のように修正し、再起動してみてください。それで提出し、ログの内容を共有してください。

```scala
for (file <- files) util.Try {
	val archive = station.archive().load(file.ref.path)
	archive.file = file.filename
	ats.archives().push(archive)
	ats.messages().push(archive)
}.recover {
	case ex => Logger(this.getClass).error(s"failed: $post", ex) // 追加された行. application.logに例外の内容を出力
}
```

**Comment by JG1VPP** [comment]
こちら、急ぎではないという感じでしょうか？例外のログを送っていただければ、いつでも対応します。

### コメント

正直、ZGPさん側で何が起こっているのかを把握できておらず。環境依存の何かが原因なのかも知れませんが。今後は、Dockerで起動する方式にすれば、例えば、Ubuntu 22.04LTSでJavaはSE11でScalaは2.13で...と言うように、我々と全く同じ環境でATS-4を起動できるようになり、ローカルの差分云々も気にする必要が減るかも。

**Comment by JG1VPP** [comment]
こちら、急ぎではないという感じでしょうか？例外のログを送っていただければ、いつでも対応します。

**Comment by JG1VPP** [comment]
今後は直接ローカルで起動せず、Dockerコンテナを立てて、その中で起動した方がデバッグ面でも楽そうですね。OSなど、我々と全く同じ環境に揃えられるので、再現がしやすいです。少なくとも、必要な環境を**全て自前で**インストールしてから`sbt`コマンドを叩いて起動するよりは、Dockerひとつをインストールして、`docker compose up`で起動する方が、覚えることが少なくて済みますし。

**Comment by karyuda** [comment]
現在立て込んでいるため、作業が遅れており申し訳ございません。
以下、例外のログになります。
コールサイン,名前,郵便番号,住所,メールアドレスは置換してあります。
ご対応よろしくお願いいたします。
```
2022-09-27 00:20:53,141 ERROR from tasks.UploadTask: failed: ContestFormData(StationFormData(コールサイン,名前,郵便番号,住所,メールアドレス,,f17a2562-83eb-43cd-b516-6be2b29e8d4b),List(SectionFormData(オールバンド部門,東京都), SectionFormData(シングルバンド 不参加,東京都), SectionFormData(シングルバンド 不参加,東京都)),List(),List())
ats4.warn.TableAccessException: org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "2022_uec_JA1ZGP.txt"; SQL statement:

INSERT INTO ARCHIVE_DATA (
        call,
        file,
        data
) VALUES(?, ?, ?); [22018-200]
        at ats4.base.AccountTable$Update.execute(AccountTable.java:166)
        at ats4.base.AccountTable.push(AccountTable.java:81)
        at tasks.UploadTask.$anonfun$accept$7(tasks.scala:78)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.util.Try$.apply(Try.scala:210)
        at tasks.UploadTask.$anonfun$accept$6(tasks.scala:75)
        at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
        at tasks.UploadTask.$anonfun$accept$1(tasks.scala:75)
        at scala.util.Try$.apply(Try.scala:210)
        at tasks.UploadTask.accept(tasks.scala:56)
        at controllers.Force.$anonfun$edit$1(controllers.scala:254)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
        at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:441)
        at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:439)
        at play.api.mvc.ActionBuilder$$anon$9.apply(Action.scala:379)
        at play.api.mvc.Action.$anonfun$apply$4(Action.scala:82)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "2022_uec_JA1ZGP.txt"; SQL statement:

INSERT INTO ARCHIVE_DATA (
        call,
        file,
        data
) VALUES(?, ?, ?); [22018-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:457)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.value.Value.convertTo(Value.java:875)
        at org.h2.value.Value.convertTo(Value.java:737)
        at org.h2.value.Value.getLong(Value.java:627)
        at org.h2.table.Column.updateSequenceIfRequired(Column.java:416)
        at org.h2.table.Column.validateConvertUpdateSequence(Column.java:399)
        at org.h2.table.Table.validateConvertUpdateSequence(Table.java:845)
        at org.h2.command.dml.Insert.insertRows(Insert.java:187)
        at org.h2.command.dml.Insert.update(Insert.java:151)
        at org.h2.command.CommandContainer.update(CommandContainer.java:198)
        at org.h2.command.Command.executeUpdate(Command.java:251)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:191)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:152)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at ats4.base.AccountTable$Update.execute(AccountTable.java:164)
        ... 28 common frames omitted
Caused by: java.lang.NumberFormatException: For input string: "2022_uec_JA1ZGP.txt"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Long.parseLong(Long.java:692)
        at java.base/java.lang.Long.parseLong(Long.java:817)
        at org.h2.value.Value.convertToLong(Value.java:1011)
        at org.h2.value.Value.convertTo(Value.java:808)
        ... 42 common frames omitted
2022-09-27 00:20:53,143 INFO from tasks.UploadTask: accept: ContestFormData(StationFormData(コールサイン,名前,郵便番号,住所,メールアドレス,,f17a2562-83eb-43cd-b516-6be2b29e8d4b),List(SectionFormData(オールバンド部門,東京都), SectionFormData(シングルバンド 不参加,東京都), SectionFormData(シングルバンド 不参加,東京都)),List(),List())
2022-09-27 00:20:53,144 INFO from play.mailer: mock implementation, send email
2022-09-27 00:20:53,145 INFO from play.mailer: subject: 電通大コンテスト書類提出の完了
2022-09-27 00:20:53,145 INFO from play.mailer: from: コールサイン<メールアドレス>
2022-09-27 00:20:53,145 INFO from play.mailer: bodyText: コールサイン様

この度は電通大コンテストに参加いただきありがとうございます。

オールバンド部門
(運用地東京都)

シングルバンド 不参加
(運用地東京都)

にて受理いたしました。
今後とも当コンテストをよろしくお願いいたします。

---
このメールに心当たりがない場合はお手数ですが下記の連絡先までご連絡ください。

---
署名略
2022-09-27 00:20:53,145 INFO from play.mailer: to: コールサイン<メールアドレス>
2022-09-27 00:20:53,145 INFO from play.mailer: bcc: メールアドレス
```

**Comment by JG1VPP** [comment]
例外の共有ありがとうございます。QxSLライブラリに問題がありそうですが、いったん、今のATS-4のディレクトリをアーカイブして送っていただけないでしょうか？
https://drive.google.com/drive/folders/1LugixmCg73fYlhL6rvybTahthDevzrfp?usp=sharing

**Comment by JG1VPP** [comment]
`ats4.mv.db`は削除してからアーカイブしてください。よろしくお願いいたします。

**Comment by karyuda** [comment]
ATS-4のディレクトリをアーカイブして送らせていただきました。
ご確認のほどよろしくお願いいたします。

**Comment by JG1VPP** [comment]
@karyuda 我々の方でテストしましたが、特に問題なく提出できました。なお、アップロードいただいたバイナリをそのまま使っています。アップロードしたファイルも無事にダウンロードできます。

**Comment by JG1VPP** [comment]
ブラウザのキャッシュクリアで解決しますか？

**Comment by karyuda** [comment]
ファイル名を拡張子も消して`1`などにすると提出できました。
ありがとうございます。

**Comment by JG1VPP** [comment]
どれくらいのファイル数になりそうですか？たくさん修正が必要な場合は手間ですよね...

**Comment by JG1VPP** [comment]
特にお困りでなければ、このIssueの内容は解決済みですので、閉じます。

**Comment by karyuda** [comment]
SWL部門、シングルバンド2部門ともに提出できました。
ファイル数はあまり多くないので、手作業で行います。
ご対応ありがとうございました。
